### ISSUE TITLE
Example To Illustrate Usage with Adafruit_NTP Library

### ISSUE THREAD

**Issue by FoamyGuy** [adafruit/Adafruit_CircuitPython_Wiznet5k#132]
It would be nice to have an example in this repo, or over in adafruit_ntp (or maybe both) that illustrates how to use wiznet5k with adafruit_ntp in order to the current from an ntp server.

**Comment by FoamyGuy** [comment]
There is a good start on this here: https://github.com/adafruit/Adafruit_CircuitPython_Wiznet5k/issues/126#issuecomment-1611786080

**Comment by anecdata** [comment]
@FoamyGuy Does https://github.com/adafruit/Adafruit_CircuitPython_NTP/pull/31 satisfy the issue, or is more work needed?

**Comment by FoamyGuy** [comment]
I think that covers it. Thank you!
