### ISSUE TITLE
File Transfer example

### ISSUE THREAD

**Issue by nopnop2002** [adafruit/Adafruit_CircuitPython_Wiznet5k#167]
Many microcontrollers now support file systems.

I would like file transfer samples such as ftp and scp.

**Comment by justmobilize** [comment]
FTP and SCP would be separate libraries, potentially too big for many MCUs. You can check the community bundle to see if anyone has built anything for that.

**Comment by nopnop2002** [comment]
A lightweight sftp might also be fine.

**Comment by justmobilize** [comment]
Here is the community bundle list: https://github.com/adafruit/CircuitPython_Community_Bundle/blob/main/circuitpython_community_library_list.md

You can also join Adafruit's Discord: http://adafru.it/discord and ask there if anyone has built anything

**Comment by nopnop2002** [comment]
OK. Thank you.
