### ISSUE TITLE
set DHCP hostname

### ISSUE THREAD

**Issue by bytelinker** [adafruit/Adafruit_CircuitPython_Wiznet5k#18]
It would be great if the hostname could be set to custom values.
eth = WIZNET5K(spi_bus, cs,is_dhcp=True,debug=True,hostname='mydevice')

Regards bytelinker

**Comment by xorbit** [comment]
I added this functionality in my pull request #20.
Verified to work with PoE-FeatherWing, can ping by hostname.

**Comment by brentru** [comment]
This functionality is now included in `v1.4.0` of this library.
